title: Mi Sitio Web
description: Portafolio personal con Jekyll y Minimal Mistakes
email: tu@email.com
url: "https://jerosuni.github.io"
baseurl: "" # Deja vacío si usas GitHub Pages

theme: minimal-mistakes-jekyll

author:
  name: Luis Jerónimo
  avatar: "/assets/images/avatar.png"
  bio: "Desarrollador web con enfoque en sitios estáticos."
  location: Guatemala

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  proyectos:
    output: true
    permalink: /proyectos/:path/

defaults:
  - scope:
      path: ""
      type: proyectos
    values:
      layout: single
      author_profile: true